CREATE TABLE users (
  id SERIAL PRIMARY KEY,
  email VARCHAR(225) UNIQUE NOT NULL,
  password_hash VARCHAR(225) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
)

CREATE INDEX idx_users_email ON users(email)
